services:
  - type: web
    name: manyumbavacant
    runtime: python
    plan: free
    region: ohio
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: manyumbavacant-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        value: "duhyohtyq"
      - key: CLOUDINARY_API_KEY
        value: "462945843189545"
      - key: CLOUDINARY_API_SECRET
        value: "eaUUwyVEEzd-ta1rGWTXD2HOhro"

databases:
  - name: manyumbavacant-db
    plan: free